sudo: false
language: node_js
node_js:
  - "node"
install: npm install
script:
  - npm run ci && npm run build
cache: npm
branches:
  only:
  - master
deploy:
  fqdn: thorkout.app
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: docs
  target_branch: gh-pages
  on:
    branch: master
